# docker-compose.yaml for Editing MongoDB Configurations
services:
  ##################################
  # MongoDB backing service 
  ##################################
  mongodb:
    image: mongo:7.0.5
    ports:
      - "127.0.0.1:27017:27017"
    extra_hosts:
      - "mongodb:127.0.0.1"
    healthcheck:
      test: echo "db.runCommand('ping')" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      retries: 3
    command: ["--bind_ip_all", "--port", "27017"]

  ##################################
  # MongoDB Configurator API - Dev Mode (mounts ./configurator to /input)
  ##################################
  configurator_api:
    image: ghcr.io/agile-learning-institute/mongodb_configurator_api:latest
    restart: no
    ports:
      - "127.0.0.1:{{info.base_port + 2}}:{{info.base_port + 2}}"
    environment:
      MONGODB_REQUIRE_TLS: False
      ENABLE_DROP_DATABASE: True
      MONGO_DB_NAME: {{info.db_name}}
      AUTO_PROCESS: False
      LOAD_TEST_DATA: True
      API_PORT: {{info.base_port + 2}}
      SPA_PORT: {{info.base_port + 3}}
      INPUT_FOLDER: /input
      UI_HEADER: "{{info.name}} DEV MongoDB Configurations"
    volumes:
      - ${INPUT_FOLDER:-./configurator}:/input
    depends_on:
      mongodb:
        condition: service_healthy

  ##################################
  # MongoDB Configurator SPA
  ##################################
  configurator_spa:
    image: ghcr.io/agile-learning-institute/mongodb_configurator_spa:latest
    restart: no
    environment:
      API_HOST: configurator_api
      API_PORT: {{info.base_port + 2}}
      SPA_PORT: {{info.base_port + 3}}
    ports:
      - "127.0.0.1:{{info.base_port + 3}}:{{info.base_port + 3}}"
    depends_on:
      configurator_api:
        condition: service_started

